# Generated by Django 3.1 on 2021-04-12 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_furnizor', models.CharField(max_length=20)),
                ('adresa_fiscala', models.CharField(max_length=20)),
                ('cod_fiscal', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Produse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_produs', models.CharField(max_length=20)),
                ('data_producerii', models.DateField(default='12-04-2021')),
                ('data_expirarii', models.DateField(default='12-04-2021')),
                ('pret', models.IntegerField(max_length=10)),
                ('barcode', models.CharField(max_length=13)),
                ('detalii', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suma_comanda', models.IntegerField(max_length=10)),
                ('data_comanda', models.DateField(default='12-04-2021')),
                ('cantitate', models.IntegerField(max_length=10)),
                ('unitate_masura', models.CharField(max_length=10)),
                ('id_furnizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.furnizor')),
                ('id_produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.produse')),
            ],
        ),
    ]
