# Generated by Django 3.1 on 2021-04-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_categorie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_producator', models.CharField(max_length=20)),
                ('tara_origine', models.CharField(max_length=10)),
                ('adresa_fiscala', models.CharField(max_length=20)),
                ('cod_fiscal', models.CharField(max_length=12)),
                ('numar_contact', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='comanda',
            old_name='id_furnizor',
            new_name='furnizor',
        ),
        migrations.RenameField(
            model_name='comanda',
            old_name='id_produs',
            new_name='produs',
        ),
        migrations.CreateModel(
            name='Vanzari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suma_vanzare', models.IntegerField(max_length=10)),
                ('data_vanzarii', models.DateField(default='12-04-2021')),
                ('cantitate', models.IntegerField(max_length=10)),
                ('unitate_masura', models.CharField(max_length=10)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.produse')),
            ],
        ),
        migrations.CreateModel(
            name='Producator_Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.categorie')),
                ('producator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.producator')),
            ],
        ),
        migrations.CreateModel(
            name='Angajat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=10)),
                ('prenume', models.CharField(max_length=10)),
                ('data_angajarii', models.DateField(default='12-04-2021')),
                ('nr_contract', models.IntegerField(max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.job')),
            ],
        ),
        migrations.AddField(
            model_name='produse',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storeapp.categorie'),
        ),
        migrations.AddField(
            model_name='produse',
            name='producator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storeapp.producator'),
        ),
    ]
