# Generated by Django 3.1 on 2021-04-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_auto_20210412_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angajat',
            name='nr_contract',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='cantitate',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='suma_comanda',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='producator',
            name='numar_contact',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='produse',
            name='pret',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vanzari',
            name='cantitate',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vanzari',
            name='suma_vanzare',
            field=models.FloatField(max_length=10),
        ),
    ]
