# Generated by Django 3.1 on 2021-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_auto_20210412_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angajat',
            name='nr_contract',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='angajat',
            name='nume',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='angajat',
            name='prenume',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='unitate_masura',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='adresa_fiscala',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='cod_fiscal',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='job',
            name='denumire',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='producator',
            name='adresa_fiscala',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producator',
            name='cod_fiscal',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='producator',
            name='tara_origine',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='produse',
            name='nume_produs',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vanzari',
            name='unitate_masura',
            field=models.CharField(max_length=15),
        ),
    ]
