# Generated by Django 3.1 on 2021-04-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_auto_20210412_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produse',
            name='data_expirarii',
            field=models.DateField(default='dd-04-2021'),
        ),
        migrations.AlterField(
            model_name='produse',
            name='data_producerii',
            field=models.DateField(default='dd-04-2021'),
        ),
    ]
