# Generated by Django 3.1 on 2021-04-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_auto_20210412_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produse',
            name='data_expirarii',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produse',
            name='data_producerii',
            field=models.DateField(auto_now=True),
        ),
    ]
