# Generated by Django 3.1 on 2021-04-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_auto_20210412_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angajat',
            name='data_angajarii',
            field=models.DateField(default='14-04-2021'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data_comanda',
            field=models.DateField(default='14-04-2021'),
        ),
        migrations.AlterField(
            model_name='produse',
            name='data_expirarii',
            field=models.DateField(default='2021-04-14'),
        ),
        migrations.AlterField(
            model_name='produse',
            name='data_producerii',
            field=models.DateField(default='2021-04-14'),
        ),
        migrations.AlterField(
            model_name='vanzari',
            name='data_vanzarii',
            field=models.DateField(default='14-04-2021'),
        ),
    ]
