# Generated by Django 3.1 on 2021-04-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0009_auto_20210414_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angajat',
            name='data_angajarii',
            field=models.DateField(default='2021-04-15'),
        ),
        migrations.AlterField(
            model_name='angajat',
            name='nr_contract',
            field=models.IntegerField(max_length=25),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data_comanda',
            field=models.DateField(default='2021-04-15'),
        ),
        migrations.AlterField(
            model_name='producator',
            name='numar_contact',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='produse',
            name='data_expirarii',
            field=models.DateField(default='2021-04-15'),
        ),
        migrations.AlterField(
            model_name='produse',
            name='data_producerii',
            field=models.DateField(default='2021-04-15'),
        ),
        migrations.AlterField(
            model_name='vanzari',
            name='data_vanzarii',
            field=models.DateField(default='2021-04-15'),
        ),
    ]
